### PR TITLE
update for latest chisel, remove toBool and chisel3.core.

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by colinschmidt** [comment]
We will need to test this with chipyard before merging.

**Comment by sequencer** [comment]
Thanks! This PR is subsequent to chipsalliance/chisel3#1730.

**Comment by sequencer** [comment]
any update on this PR?

**Comment by sequencer** [comment]
I think it's safe to merge:
related to chipsalliance/chisel3#1730 :
```
diff --git a/core/src/main/scala/chisel3/Bits.scala b/core/src/main/scala/chisel3/Bits.scala
index c86e92085..17829143b 100644
--- a/core/src/main/scala/chisel3/Bits.scala
+++ b/core/src/main/scala/chisel3/Bits.scala
@@ -29,15 +29,6 @@ private[chisel3] sealed trait ToBoolable extends Element {
 
   /** @group SourceInfoTransformMacro */
   def do_asBool(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Bool
-
-  /** Casts this $coll to a [[Bool]]
-    *
-    * @note The width must be known and equal to 1
-    */
-  final def toBool(): Bool = macro SourceInfoWhiteboxTransform.noArg
-
-  /** @group SourceInfoTransformMacro */
-  def do_toBool(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Bool
 }
 
 /** A data type for values represented by a single bitvector. This provides basic bitwise operations.
@@ -315,11 +306,6 @@ sealed abstract class Bits(private[chisel3] val width: Width) extends Element wi
   /** Returns the contents of this wire as a [[scala.collection.Seq]] of [[Bool]]. */
   final def toBools(): Seq[Bool] = macro SourceInfoTransform.noArg
 
-  /** @group SourceInfoTransformMacro */
-  @chiselRuntimeDeprecated
-  @deprecated("Use asBools instead", "3.2")
-  def do_toBools(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Seq[Bool] = do_asBools
-
   /** Returns the contents of this wire as a [[scala.collection.Seq]] of [[Bool]]. */
   final def asBools(): Seq[Bool] = macro SourceInfoTransform.noArg
 
@@ -369,10 +355,6 @@ sealed abstract class Bits(private[chisel3] val width: Width) extends Element wi
     }
   }
 
-  @chiselRuntimeDeprecated
-  @deprecated("Use asBool instead", "3.2")
-  final def do_toBool(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Bool = do_asBool
-
```

**Comment by colinschmidt** [comment]
@alonamid Is going to make the chipyard PR that incorporates this and the other deprecation fixes you've made recently.

**Comment by sequencer** [comment]
Hi @colinschmidt, can we get this in now? :)

**Comment by sequencer** [comment]
ping

**Comment by jerryz123** [comment]
@sequencer Were you going to open a Chipyard PR aggregating all your bumps?

**Comment by sequencer** [comment]
Sure :)
 f

**Comment by davidbiancolin** [comment]
These are not RTL changing, the same changes have been made in multiple submodules, so i'm going to green light this as it helps with my chisel bump. 

I will be making the aggregating bump in CY.

**Review by davidbiancolin — APPROVED** [review]

**Pull request merged**
