### PR TITLE
Flip serialized tilelink clock source

### PR DESCRIPTION
**Pull request by jerryz123**
Generate the clock off-chip, instead of relying on the on-chip clock

### CODE REVIEW

**Review by harrisonliew — CHANGES_REQUESTED** [review]
SimSerial needs to have its clock direction flipped too, right?
Also comment about using serial_tl_domain's reset seems reasonable - it get's sync'd over the clock crossing?

**Comment by jerryz123** [comment]
This shouldn't affect SimSerial, since that is a simulation-only construct. This only affects the serialized tilelink interface between the harness (or FPGA) and the chip.

**Comment by jerryz123** [comment]
Hmm, I think the reset on the external side needs to be sync'd

**Comment by harrisonliew** [comment]
> This only affects the serialized tilelink interface between the harness (or FPGA) and the chip.

When generating the harness/FPGA interface, how does its clock get flipped properly? Do the XDC constraints need to be updated too?

**Review by T-K-233 — APPROVED** [review]
✓

**Pull request merged**
