### PR TITLE
Bump sbt to something less dangerous and don't ignore non-target project files.

### PR DESCRIPTION
**Pull request by ucbjrl**

### CODE REVIEW

**Comment by colinschmidt** [comment]
Do all consuming projects need to bump sbt at the same time?

**Comment by ucbjrl** [comment]
I don't believe it's strictly necessary, although to minimize the effect of potential sbt weirdness, we should try to keep them consistent.

Ideally, this can be packaged as a library and the version of sbt used to build it should have no impact on its use by clients.

Perhaps we should discuss packaging and publishing before this PR is approved (or rejected).

**Comment by kammoh** [comment]
Any reasons not upgrading to 1.3.0?

**Comment by ucbjrl** [comment]
I'd like to see firrtl and chisel3 upgraded to sbt 1.3.0 first.

**Comment by ucbjrl** [comment]
Presumably handled elsewhere.

**Pull request closed without merging**
