### PR TITLE
FIX (improve-boot-1): change reset vector address and boot register address

### PR DESCRIPTION
**Pull request by T-K-233**
Change reset vector PC address to 0x10000. This makes more sense, and users can override BOOTROM with their own code when testing.

### CODE REVIEW

**Comment by T-K-233** [comment]
Note: this depends on [rocket-chip #3328](https://github.com/chipsalliance/rocket-chip/pull/3328)

**Comment by jerryz123** [comment]
This should not require rocketchip changes. In Chipyard you can change the withbootrom config fragment to also set hang

**Comment by tianrui-wei** [comment]
Note that this PR can be potentially disruptive as we are trying to bring in force support

**Comment by jerryz123** [comment]
From a separate discussion, I think we will not change the default bootrom. Instead we will improve support for custom next stage bootloaders.

**Comment by T-K-233** [comment]
> Note that this PR can be potentially disruptive as we are trying to bring in force support

Sorry I don't quite understand, what do you mean by "bring in force support"...?

**Comment by tianrui-wei** [comment]
Sorry for the confusion. For context, we're using force-riscv in another branch. This PR looks very good and I'm fine with it being merged as long as Jerry approves it. This is more of a note to Jerry as we try to upstream things.

**Pull request closed without merging**
