### PR TITLE
Add "override lazy" to Generator.longName to sync with rocket-chip update.

### PR DESCRIPTION
**Pull request by ucbjrl**
See chipsalliance/rocket-chip#2049

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Should this change be echoed in the Chipyard area (generators/example/...)? Also, has this been confirmed to work with Chipyard? Finally, what is this Generator used for?

**Comment by ucbjrl** [comment]
Great questions @abejgonzalez. @grebe added this repository to [chisel-release](https://github.com/ucb-bar/chisel-release) (ucb-bar/chisel-release#5) on the assumption that it would be published with rocket-chip. If it has more dependencies, it should probably be removed from chisel-release, and managed along with its dependencies. (I'm still not sure chisel-release should include rocket-chip. Although we're currently publishing master SNAPSHOTS, I think this role should be moved to Chipyard or SiFive).

**Comment by abejgonzalez** [comment]
The only dependency is Rocket Chip so it should be fine to bundle with `chisel-release`. I still don't follow why there is a generator here? My impression is that the SoC projects (`rocketchip`, `chipyard`, etc) will have their own generators which will be invoked. There will not be a Generator invoked from `testchipip`.

**Comment by ucbjrl** [comment]
Presumably handled elsewhere.

**Pull request closed without merging**
