### PR TITLE
Updating build.sbt as a precursor to updating Maven

### PR DESCRIPTION
**Pull request by tianrui-wei**

### CODE REVIEW

**Comment by tianrui-wei** [comment]
This commit bumps `build.sbt` in preperation for bumping the published version on maven, which is ~3 years old at this point.

**Comment by jerryz123** [comment]
I feel like this will break when testchipip is built with chipyard, since the chipyard testchipip project will inherit these settings.

**Comment by jerryz123** [comment]
The dependency on sifive-blocks is regrettable. IMO we should refactor the stuff that depends on sifive-blocks out of this into chipyard directly.

UARTAdapter and SPIFlash can both go in chipyard. Then testchipip only needs rocket-chip

**Comment by tianrui-wei** [comment]
I feel chipyard should override the dependency in its settings when you flip on a development switch, in which case it will clone dependencies as submodules. But in default mode, it should just use binary dependency off maven.

Until we figure out how to publish CY as a maven package, I'd avoid moving stuff into chipyard, as the original intention would be enabling stand-alone use of packages, rather than have everything depend on chipyard.

**Comment by jerryz123** [comment]
> I feel chipyard should override the dependency in its settings when you flip on a development switch, in which case it will clone dependencies as submodules. But in default mode, it should just use binary dependency off maven.

Ok, I think that might be ok for now, but I think we should avoid adding more overrides to chipyard's build.sbt.

**Comment by tianrui-wei** [comment]
Sorry for the blip, restored the old master branch

**Comment by jerryz123** [comment]
I meant open a PR for chipyard, then we merge that PR and this one at the same time, once we confirm the chipyard changes work. 

Its not a big deal, but I stlil reverted your changes for now, also so we can get feedback from @abejgonzalez and others

**Comment by tianrui-wei** [comment]
Sounds good, yeah sorry for the wrong push. I was meaning to push to my own fork... Thanks for the help.

Actually this depends on https://github.com/chipsalliance/rocket-chip-blocks/pull/9 so this should probably not be merged until that one is merged and a maven package is already upstream

**Comment by tianrui-wei** [comment]
CY PR opened at https://github.com/ucb-bar/chipyard/pull/1299, new PR at https://github.com/ucb-bar/testchipip/pull/153

**Comment by jerryz123** [comment]
For Chipyard I mean a chipyard PR that bumps testchipip submodule, and fixes and issues with build.sbt.

**Comment by tianrui-wei** [comment]
Oh I see lol

**Pull request merged**
